SUBROUTINE PART_PDF
!----------------------------------------------------------------------
!...Author: Derrick Ovunda Njobuenwu d.o.njobuenwu@leeds.ac.uk
!...Date:	Moday November 14 2011 13:37:30 GMT
!
!...No part of this code can be modified without
!   written permission from the Author. Mon November 14 2011 13:37:30 GMT
!----------------------------------------------------------------------
!
!
USE  FDIM_MODULE
USE  FGRID_MODULE
USE  FVAR_MODULE
USE  FTURB_MODULE
USE  FTIME_MODULE
USE  FFILE_MODULE
USE  PART_NUM_MODULE
USE  PART_COUNT_MODULE
USE  PART_INITIAL_MODULE
USE  PART_LOGICAL_MODULE
USE  PART_STAT_MODULE
USE  PART_VECTOR_MODULE
USE  PART_TIME_MODULE
USE  PART_PROP_MODULE
USE  PART_EXTRA_MODULE
USE  PART_SGS_MODULE
USE  GEO_SIZE_MODULE
USE  PART_CONCEN_MODULE
USE  PART_FILENAME_MODULE
USE  PART_PDF_MODULE
USE  FUTILITY_MODULE
USE  PART_PSTATE_MODULE
USE  PART_RSTATE_MODULE


IMPLICIT NONE
INTEGER	::	J,II,NOV,CC
INTEGER	::	UNITP(8)
DOUBLE PRECISION	::	SPTIM
CHARACTER	(LEN=120)	::	AFILE(8)
REAL	::	RADA,DIAP,ESDV,LAMBDA,MASS,RADIUS,RHOD,PST
INTEGER, DIMENSION(30) :: CYLINDERPDF ! ARRAY TO STORE NUMBER OF PARTICLES IN THAT CYLINDER
INTEGER, DIMENSION(30) :: ROWPDF
REAL, DIMENSION(30) :: VELUPDF, VELVPDF, VELWPDF

DATA UNITP /801,802,803,804,805,806,807,808/

NOV=5

IF(.NOT.ALLOCATED(OMEGAF))ALLOCATE(OMEGAF(ND))

DO ISET=1,NPSET
   !:::::::::::::::::::::::::::::::
   LAMBDA   =  PSTATE(01,ISET)
   RADA     =  PSTATE(02,ISET)
   ESDV     =  PSTATE(03,ISET)
   PST      =  PSTATE(04,ISET)
   MASS     =  PSTATE(05,ISET)
   RHOD     =  PSTATE(06,ISET)
   DIAP     =  ESDV
   RADIUS   =  0.5*ESDV

   !=== ZERO THE ARRAY, READY FOR NEXT SAMPLE ===!
   DO CC=1,30
    CYLINDERPDF(CC) = 0
    ROWPDF(CC) = 0
    VELUPDF(CC) = 0
    VELVPDF(CC) = 0
    VELWPDF(CC) = 0
   END DO
   !=== END OF ARRAY ZEROING ===!

   WRITE(AFILE(1),900)TRIM(PART_PDF_FILE)//'RET',NINT(RET),'_ALLPARTPOSXY_'//TRIM(SHAPE(ISET))//'_',INT(PST_SET(ISET)),'_ISET',ISET,'_ISTEP',ISTEP
   WRITE(AFILE(2),900)TRIM(PART_PDF_FILE)//'RET',NINT(RET),'_TURBOVELL_'//TRIM(SHAPE(ISET))//'_',INT(PST_SET(ISET)),'_ISET',ISET,'_ISTEP',ISTEP
   WRITE(AFILE(3),900)TRIM(PART_PDF_FILE)//'RET',NINT(RET),'_PARTTRACK_'//TRIM(SHAPE(ISET))//'_',INT(PST_SET(ISET)),'_ISET',ISET,'_ISET',ISET
   OPEN(UNITP(1),FILE=AFILE(1),STATUS='UNKNOWN',FORM='FORMATTED',POSITION='APPEND')
   OPEN(UNITP(2),FILE=AFILE(2),STATUS='UNKNOWN',FORM='FORMATTED',POSITION='APPEND')

   DO IP=1,NPAR
      JPART=IP+(ISET-1)*NPART
      IF(LAMBDA /= 1)THEN
         !WRITE(AFILE(1),900)TRIM(PART_PDF_FILE)//'RET',NINT(RET),'_ORIENTAT_'//TRIM(SHAPE(ISET))//'_',INT(PST_SET(ISET)),'_ISET',ISET,'_POS',IP
         !WRITE(AFILE(2),900)TRIM(PART_PDF_FILE)//'RET',NINT(RET),'_ROTATION_'//TRIM(SHAPE(ISET))//'_',INT(PST_SET(ISET)),'_ISET',ISET,'_POS',IP
         !WRITE(AFILE(3),900)TRIM(PART_PDF_FILE)//'RET',NINT(RET),'_TRAJ_ORIENT_'//TRIM(SHAPE(ISET))//'_',INT(PST_SET(ISET)),'_ISET',ISET,'_POS',IP
      END IF
      !WRITE(AFILE(4),900)TRIM(PART_PDF_FILE)//'RET',NINT(RET),'_LINEAR00_'//TRIM(SHAPE(ISET))//'_',INT(PST_SET(ISET)),'_ISET',ISET,'_POS',IP
      !WRITE(AFILE(5),900)TRIM(PART_PDF_FILE)//'RET',NINT(RET),'_PROPERTY_'//TRIM(SHAPE(ISET))//'_',INT(PST_SET(ISET)),'_ISET',ISET,'_POS',IP
      !WRITE(AFILE(5),900)TRIM(PART_PDF_FILE)//'RET',NINT(RET),'_SLIP_ACC_'//TRIM(SHAPE(ISET))//'_',INT(PST_SET(ISET)),'_ISET',ISET,'_POS',IP
      WRITE(AFILE(4),900)TRIM(PART_PDF_FILE)//'RET',NINT(RET),'_TURBO_'//TRIM(SHAPE(ISET))//'_',INT(PST_SET(ISET)),'_ISET',ISET,'_ISTEP',ISTEP
      WRITE(AFILE(5),900)TRIM(PART_PDF_FILE)//'RET',NINT(RET),'_TURBOGRAV_'//TRIM(SHAPE(ISET))//'_',INT(PST_SET(ISET)),'_ISET',ISET,'_ISTEP',ISTEP

      SPTIM=LPTTIME*WTIM
      DO J=1,NOV
         IF(LAMBDA == 1 .AND. J <= 3)THEN
            !DO NOTHING
         ELSE
            !OPEN(UNITP(J),FILE=AFILE(J),STATUS='UNKNOWN',FORM='FORMATTED',POSITION='APPEND')
         END IF
      END DO
      IF(LAMBDA /= 1)THEN         !
         !-----------------------
         !OBTAIN FLUID ROTATION IN INERTIAL FRAME
         CALL PART_FLUID_TRANS(0)
         !-----------------------
         IF(LAMBDA_SET(ISET) /= 1.0)THEN
            !---------------
            CALL PART_MATRIX
            !---------------
            !-----------------------
            !TRANSFORM PARTICLE ROTATION FROM PARTICLE FRAME TO INERTIAL FRAME
            CALL PART_FLUID_TRANS(2)
            !-----------------------
         END IF
         !ANGULAR POSITION (ORIENTATION) AND VELOCITY (ROTATION):  TIME, X', Y', Z';
         !
         !WRITE(UNITP(1),901)SPTIM,(TMA(3,II),II=1,ND),(ACOS(TMA(3,II))*RAD2DEG,II=1,ND)
         !ANGULAR ACCELERATION THFX,TRRX,TOPX,THFY,TRRY,TOPY
         !WRITE(UNITP(2),901)SPTIM,(TORQ(II,JPART),II=1,6)
         !ROTATONAL VELOCITY: FLUID OMEGAFX,OMEGAFY,OMEGAFZ; SLIP SPIN (OMEGAF - OMEGA)
         !WRITE(UNITP(2),902)SPTIM,(ROT(II+ND,JPART)/WTIM,II=1,ND),((FROTX(II) - PROT_FIXED(II))/WTIM,II=1,ND)
         !WRITE(UNITP(3),'(a)')"ZONE"
         !WRITE(UNITP(3),901)(PART(II,JPART)*WLEN,II=1,ND),(ROT(II+ND,JPART)/WTIM,II=1,ND),(PART(II+ND,JPART)*WVEL,II=ND,ND)

      END IF
      !LINEAR POSITION AND VELOCITY: TIME, XP,YP,ZP; UP,VP,WP
      !WRITE(UNITP(4),901)SPTIM,(PART(II,JPART)*WLEN,II=1,ND),(PART(II+ND,JPART)*WVEL,II=1,ND)
      !PROPETIES: ALPHA;      REP,CD
      !WRITE(UNITP(5),902)SPTIM,PIN(05,JPART)*RAD2DEG,PIN(02,JPART),PIN(03,JPART)
      !LINEAR SLIP VELOCITY AND ACCELEARATION;,(U-UP),(V-VP),(W-WP)   AU, AV, AW

      !=== DETERMINE WHAT CYLINDER THE PARTICLE IS IN ===!
      DO CC=1,30
        IF(SQRT((PART(1,JPART)**2)+(PART(2,JPART)**2)) .LE. FLOAT(CC)*0.02D0/30.0D0 .AND. SQRT((PART(1,JPART)**2)+(PART(2,JPART)**2)) .GE. FLOAT(CC-1)*0.02D0/30.0D0) THEN
        CYLINDERPDF(CC) = CYLINDERPDF(CC) + 1
        VELUPDF(CC) = VELUPDF(CC) + PART(4,JPART)
        VELVPDF(CC) = VELVPDF(CC) + PART(5,JPART)
        VELWPDF(CC) = VELWPDF(CC) + PART(6,JPART)
        END IF
      END DO
      !=== END OF CYLINDER DETERMINATION ===!

      !=== DETERMINE WHAT ROW THE PARTICLE IS IN ===!
      DO CC=1,30
        IF(PART(2,JPART) .LE. (-0.02D0+(FLOAT(CC)*0.04D0/30.0D0)) .AND. PART(2,JPART) .GE. (-0.02D0+(FLOAT(CC-1)*0.04D0/30.0D0))) THEN
        ROWPDF(CC) = ROWPDF(CC) + 1
        END IF
      END DO
      !=== END OF ROW DETERMINATION ===!
	  IF (IP == 1) THEN
	   OPEN(UNITP(3),FILE=AFILE(3),STATUS='UNKNOWN',FORM='FORMATTED',POSITION='APPEND')
	   WRITE(UNITP(3),904) PART(1,JPART),' ',PART(2,JPART),' ',PART(3,JPART)
	  END IF

      WRITE(UNITP(1),904) PART(1,JPART),' ',PART(2,JPART),' ',PART(3,JPART)
   END DO

   !=== OUTPUT POSITION PDF ===!
   OPEN(UNITP(4),FILE=AFILE(4),STATUS='UNKNOWN',FORM='FORMATTED',POSITION='APPEND')
   OPEN(UNITP(5),FILE=AFILE(5),STATUS='UNKNOWN',FORM='FORMATTED',POSITION='APPEND')

   !WRITE(UNITP(6),*) ISTEP
   DO CC=1,30
     WRITE(UNITP(4),903) CC*0.02D0/30.0D0,' ',CYLINDERPDF(CC)
     WRITE(UNITP(5),903) (-0.02D0+FLOAT(CC)*0.04D0/30.0D0),' ',ROWPDF(CC)
     IF (CYLINDERPDF(CC) /= 0) THEN
        WRITE(UNITP(2),905) CC*0.02D0/30.0D0,' ',VELUPDF(CC)/CYLINDERPDF(CC),' ',VELVPDF(CC)/CYLINDERPDF(CC),' ',VELWPDF(CC)/CYLINDERPDF(CC)
     ELSE
        WRITE(UNITP(2),905) CC*0.02D0/30.0D0,' ',1,' ',1,' ',1
     END IF
   END DO
   !=== END OF OUTPUTTING POSITION PDF ===!

   !=== ZERO THE ARRAY, READY FOR NEXT SAMPLE ===!
   DO CC=1,30
    CYLINDERPDF(CC) = 0
    ROWPDF(CC) = 0
    VELUPDF(CC) = 0
    VELVPDF(CC) = 0
    VELWPDF(CC) = 0
   END DO
   !=== END OF ARRAY ZEROING ===!

END DO

PDFCOUNT = PDFCOUNT + 1

!
!******************************			FORMATS			***********************************
900    FORMAT(A,I6.6,3(A,I7.7))
901    FORMAT(9(1PE16.8))
903    FORMAT(1PE16.8,A,I8.8)
904    FORMAT(1PE16.8,A,1PE16.8,A,1PE16.8)
905    FORMAT(1PE16.8,A,1PE16.8,A,1PE16.8,A,1PE16.8)
902    FORMAT(8(1PE16.8))
!
  IF(ALLOCATED(TORQUE))  DEALLOCATE(TORQUE)

 RETURN
 END SUBROUTINE PART_PDF
