!
!======================================================================
!
!*******3D NON-SPHERICAL PARTICLE TRACKER SUBROUTINES BEGIN************
!
!======================================================================
!
!
!*********************	  PARAMETERS	  *****************************
!
SUBROUTINE PART_BC_CHANNEL
!
USE  FDIM_MODULE
USE  FGRID_MODULE
USE  FFILE_MODULE
USE  PART_NUM_MODULE
USE  PART_COUNT_MODULE
USE  PART_INITIAL_MODULE
USE  PART_LOGICAL_MODULE
USE  PART_STAT_MODULE
USE  PART_VECTOR_MODULE
USE  PART_TIME_MODULE
USE  PART_PROP_MODULE
USE  PART_EXTRA_MODULE
USE  PART_SGS_MODULE
USE  PART_PSTATE_MODULE
USE  PART_RSTATE_MODULE
USE  FTURB_MODULE
USE  PART_PWI_MODULE
USE  PART_FLAG_MODULE
!
IMPLICIT NONE
!
INTEGER		      :: HITMAX
DOUBLE PRECISION 	:: DISTANCE,TIMEDEPOSIT,HREB,XREB,YREB,ANGVEL,ANGR,EXTDIST,TWICEPF
DOUBLE PRECISION	:: LAMBDA,MASS

DATA	HITMAX/10/

EN = 1.0

LAMBDA = PSTATE(01,ISET)
MASS	 = PART(10,JPART)

309	FORMAT(4(A,1X,1PE18.8,1X))
!
IF(PWITYPE == 0)THEN
   !-----------------------------------
   !WALL-NORMAL DIRECTION: NORTH SOUTH EAST WEST(WALL)
   !-----------------------------------
   NHIT = HITMAX
   IHIT = 0
   10	CONTINUE
   IF(SQRT(PART(1,JPART)**2 + PART(2,JPART)**2) > BWALL_HIT(2)) THEN
	  !WRITE(SCRN,*)'COLLISION CODE RUNNING'
      IHIT = IHIT + 1
      IF(IHIT > NHIT) THEN
         CALL PART_MESSAGE(300)
      END IF
	  ANGVEL = ATAN(PART(5,JPART)/PART(4,JPART))
	  !WRITE(SCRN,*)'ANGVEL = ',ANGVEL
	  ANGR = ATAN(PART(2,JPART)/PART(1,JPART))
	  !WRITE(SCRN,*)'ANGR = ',ANGR
	  EXTDIST = SQRT(PART(1,JPART)**2 + PART(2,JPART)**2) - BWALL_HIT(2)
	  !WRITE(SCRN,*)'EXTDIST = ',EXTDIST
      XREB = EXTDIST*COS(ANGR)
	  !WRITE(SCRN,*)'TRANSLATION IN X = ',-1*XREB
	  YREB = EXTDIST*SIN(ANGR)
	  !WRITE(SCRN,*)'TRANSLATION IN Y = ',-1*YREB
      !PART(1,JPART) = PART(1,JPART) - XREB
	  !PART(2,JPART) = PART(2,JPART) - YREB
	  PART(1, JPART) = PART0(1, JPART)
	  PART(2, JPART) = PART0(2, JPART)
	  !WRITE(SCRN,*)'NEW X: ',PART(1,JPART)
	  !WRITE(SCRN,*)'NEW Y: ',PART(2,JPART)
	  TWICEPF = 2*(PART(1,JPART)*PART(4,JPART) + PART(2,JPART)*PART(5,JPART))/(BWALL_HIT(2)**2)
      PART(4,JPART) = PART(4,JPART)-TWICEPF*PART(1,JPART)
	  PART(5,JPART) = PART(5,JPART)-TWICEPF*PART(2,JPART)
      CROSS_S(ISET) = CROSS_S(ISET) + 1
      GOTO 10
   END IF
ELSE IF(PWITYPE == 1)THEN
   !--------------------------------------------------------
   !WALL-NORMAL DIRECTION: NORTH-SOUTH (WALL) FOR DEPOSITION
   !--------------------------------------------------------
   IF(PART(1,JPART) > BWALL_HIT(1))THEN
      DISTANCE = DABS(PART0(1,JPART) - BWALL(1))
      TIMEDEPOSIT = DISTANCE / DABS(PART(4,JPART))
      PART(1,JPART) = PART0(1,JPART) + UPAVG * TIMEDEPOSIT - MINI_WALL_DIST
      PART(2,JPART) = PART0(2,JPART) + VPAVG * TIMEDEPOSIT
      PART(3,JPART) = PART0(3,JPART) + WPAVG * TIMEDEPOSIT
      PART(4,JPART) = -PART(4,JPART)

   ELSE IF(PART(1,JPART) < BWALL_HIT(2)) THEN
      DISTANCE = DABS(PART0(1,JPART) - BWALL(2))
      TIMEDEPOSIT = DISTANCE / DABS(PART(4,JPART))
      PART(1,JPART) = PART0(1,JPART) + UPAVG * TIMEDEPOSIT + MINI_WALL_DIST
      PART(2,JPART) = PART0(2,JPART) + VPAVG * TIMEDEPOSIT
      PART(3,JPART) = PART0(3,JPART) + WPAVG * TIMEDEPOSIT
      PART(4,JPART) = -PART(4,JPART)

   ELSE IF(PART(1,JPART) == BWALL_HIT(1) .OR. PART(1,JPART) == BWALL_HIT(2))THEN
      PART(4,JPART) = -PART(4,JPART)
   END IF
END IF
!
RETURN
END SUBROUTINE PART_BC_CHANNEL
