SUBROUTINE PART_INPUT
!----------------------------------------------------------------------
!...Author: Derrick Ovunda Njobuenwu d.o.njobuenwu@leeds.ac.uk
!...Date:	Moday November 14 2011 13:37:30 GMT
!
!...No part of this code can be modified without
!   written permission from the Author. Mon November 14 2011 13:37:30 GMT
!----------------------------------------------------------------------
!
USE  FDIM_MODULE
USE  FPROP_MODULE
USE  FGRID_MODULE
USE  FFILE_MODULE
USE  PART_NUM_MODULE
USE  PART_COUNT_MODULE
USE  PART_INITIAL_MODULE
USE  PART_LOGICAL_MODULE
USE  PART_STAT_MODULE
USE  PART_VECTOR_MODULE
USE  PART_TIME_MODULE
USE  PART_PROP_MODULE
USE  PART_EXTRA_MODULE
USE  PART_SGS_MODULE
USE  GEO_SIZE_MODULE
USE  PART_CONCEN_MODULE
USE  PART_FILENAME_MODULE
USE  FTURB_MODULE
USE  FLOGICAL_MODULE
USE  PART_PDF_MODULE
USE  FTIME_MODULE
USE  FUTILITY_MODULE
USE  PART_TWOWAY_MODULE
USE  PART_FLAG_MODULE
USE  PART_PSTATE_MODULE
USE  PART_RSTATE_MODULE
USE  PART_COLLISION_MODULE
!
IMPLICIT NONE
!
REAL	::	PVOLS,PVOL,VTEMP
REAL	::	PASA,ESDA,SPHVOL
REAL	::	RADA,RADC,ESDV,MASS,PSN,CCF,RHO_PF
REAL	::	BETA,BETA_SQ
REAL  :: RK1,RK2,ATANH,ASIN
REAL	::	MOMX,MOMY,MOMZ
INTEGER	::	IJ,IK,JK
!
WRITE(SCRN,*)'LPT ENTRES PART_INPUT SUBROUTINE'
!
!*********************
CALL PART_ALLOCATE(30)
!*********************
!PARTICLE INITIAL DISTRIBUTION
!
PSTATE = 0.0
PART = 0.0
PART0 = 0.0
PIN = 0.0
NPAR = 0
PARTMESH = .FALSE.
!KB = BOLTZMANN CONSTANT = 1.3806488 × 10-23 m2 kg s-2 K-1
KB = 1.3806488E-23
FREE_LEN = 0.066E-6 ! UNIT METER
!
!OPEN FILE: UNIT = 200
!-----------------------
CALL PART_OPENFILES(200)
!-------------------------------
!WRITE MESSAGE TO FILE: UNIT 200
!-------------------------------
CALL PART_MESSAGE(200)
!-----------------------
DO ISET=1,NPSET
   BETA = LAMBDA_SET(ISET)
   BETA_SQ = BETA*BETA

   RHO_PF = DENP_SET(ISET)/RHOAIR          ! PARTICLE/FLUID DENSITY

   IF(PARTSIZING.EQ.1)THEN
      !SPECIFY PARTICLE SIZE USING DIAMETER IN MICROMETER
      DIAP_SET(ISET) = DIAP_SET(ISET)*1.0D-6
      ESDV = DIAP_SET(ISET)
      RADA =  ESDV/(2*LAMBDA_SET(ISET)**ONETHIRD)

      IF(PARTCCF == 1)THEN
   		CCF = 1.0 + 2*FREE_LEN/ESDV*(1.257D0 + 0.4*EXP(-0.55D0*ESDV/FREE_LEN))
   	  ELSE IF(PARTCCF == 0)THEN
      	CCF = 1.0
   	  END IF

      VTEMP = ESDV*WLEN

      IF(LFORCE(6) == 1)THEN
         PST_SET(ISET) = (CCF*(VTEMP*VTEMP)*(RHO_PF + 0.5D0))/18.0D0
      ELSE
         PST_SET(ISET) = (CCF*(VTEMP*VTEMP)*RHO_PF)/18.0D0
      END IF

      WRITE(SCRN,'(A,1PE20.12)')'PST_SET = ',PST_SET(ISET)

   ELSE IF(PARTSIZING.EQ.2)THEN
      !SPECIFY PARTICLE SIZE USING PARTICLE STOKES (SHEAR) NUMBER FOR EQUIVALENT VOLUME DIAMETER
      IF(LFORCE(6) == 1)THEN
         ESDV = SQRT(PST_SET(ISET)*18.0D0/(RHO_PF + 0.5D0))
      ELSE
         ESDV = SQRT(PST_SET(ISET)*18.0D0/RHO_PF) ! D_p+ BASED ON t_p+
      END IF
      ESDV = ESDV/WLEN ! REDIMENSIONALIZE ESDV USING WLEN
      PVOLS = PIE*(1.0D0/6.0D0)*ESDV**3
      RADA = (PVOLS/(FOURTHIRD*LAMBDA_SET(ISET)*PIE))**ONETHIRD
      DIAP_SET(ISET) = ESDV

      !=== OUTPUT SOME VARIABLES TO CHECK PARTICLE PROPERTIES ARE CORRECT ===!
      WRITE(SCRN,'(A)')'================================'
      WRITE(SCRN,'(A,I1)')'PARTICLE PROPERTIES FOR NSET = ',ISET
      WRITE(SCRN,'(A)')'================================'
      WRITE(SCRN,'(A,1PE20.12)')'PST_SET: STOKES NUMBER = ',PST_SET(ISET)
	  WRITE(SCRN,'(A,1PE20.12)')'DIAP_SET: PARTICLE DIAMETER (m) = ',DIAP_SET(ISET)
	  WRITE(SCRN,'(A,1PE20.12)')'DIAP_SET / D = ',DIAP_SET(ISET) / 0.04D0
	  WRITE(SCRN,'(A,1PE20.12)')'DIAP_SET CALCULATED FROM THEORY (BULK) = ',SQRT((PST_SET(ISET)*18.0D0*NU*0.04D0)/(RHO_PF*UBULK))
	  WRITE(SCRN,'(A,1PE20.12)')'DIAP_SET / D = ',DIAP_SET(ISET) / 0.04D0
	  WRITE(SCRN,'(A,1PE20.12)')'RELAXATION TIME (s) = ', ((RHO_PF*DIAP_SET(ISET)**2)/(18.0D0*NU))
	  WRITE(SCRN,'(A,1PE20.12)')'RELAXATION TIME (+) = ', (((RHO_PF*DIAP_SET(ISET)**2)/(18.0D0*NU))/(NU/(UTAU**2)))
	  WRITE(SCRN,'(A,1PE20.12)')'RELAXATION TIME (*) = ', ((RHO_PF*DIAP_SET(ISET)**2)/(18.0D0*NU))/(0.04/UTAU)
	  WRITE(SCRN,'(A)')' '

      IF(PARTCCF == 1)THEN
   		 CCF = 1.0 + 2*FREE_LEN/DIAP_SET(ISET)*(1.257D0 + 0.4*EXP(-0.55D0*DIAP_SET(ISET)/FREE_LEN))
   	  ELSE if(PARTCCF == 0)then
      	 CCF = 1.0
   	  END IF

	ELSE IF(PARTSIZING.EQ.3)THEN
      !SPECIFY PARTICLE SIZE USING PARTICLE STOKES (BULK) NUMBER FOR EQUIVALENT VOLUME DIAMETER
      IF(LFORCE(6) == 1)THEN
         ESDV = SQRT(PST_SET(ISET)*18.0D0*NU*0.04D0/((RHO_PF + 0.5D0)*UBULK)) ! ESDV = EQUIVALENT VOLUME DIAMETER, RHO_PF = DENSITY RATIO PARTICLE TO FLUID
      ELSE
         ESDV = SQRT(PST_SET(ISET)*18.0D0*NU*0.04D0/(RHO_PF*UBULK)) !D_p BASED ON t_f
      END IF
      PVOLS = PIE*(1.0D0/6.0D0)*ESDV**3
      RADA = (PVOLS/(FOURTHIRD*LAMBDA_SET(ISET)*PIE))**ONETHIRD
      DIAP_SET(ISET) = ESDV

      !=== OUTPUT SOME VARIABLES TO CHECK PARTICLE PROPERTIES ARE CORRECT ===!
      WRITE(SCRN,'(A)')'================================'
      WRITE(SCRN,'(A,I1)')'PARTICLE PROPERTIES FOR NSET = ',ISET
      WRITE(SCRN,'(A)')'================================'
      WRITE(SCRN,'(A,1PE20.12)')'PST_SET: STOKES NUMBER (BULK) = ',PST_SET(ISET)
	  WRITE(SCRN,'(A,1PE20.12)')'DIAP_SET: PARTICLE DIAMETER (m) = ',DIAP_SET(ISET)
	  WRITE(SCRN,'(A,1PE20.12)')'DIAP_SET / D = ',DIAP_SET(ISET) / 0.04D0
	  WRITE(SCRN,'(A,1PE20.12)')'DIAP_SET CALCULATED FROM THEORY (BULK) = ',SQRT((PST_SET(ISET)*18.0D0*NU*0.04D0)/(RHO_PF*UBULK))
	  WRITE(SCRN,'(A,1PE20.12)')'DIAP_SET / D = ',DIAP_SET(ISET) / 0.04D0
	  WRITE(SCRN,'(A,1PE20.12)')'RELAXATION TIME (s) = ', ((RHO_PF*DIAP_SET(ISET)**2)/(18.0D0*NU))
	  WRITE(SCRN,'(A,1PE20.12)')'RELAXATION TIME (+) = ', (((RHO_PF*DIAP_SET(ISET)**2)/(18.0D0*NU))/(NU/(UTAU**2)))
	  WRITE(SCRN,'(A,1PE20.12)')'RELAXATION TIME (*) = ', ((RHO_PF*DIAP_SET(ISET)**2)/(18.0D0*NU))/(0.04/UTAU)
	  WRITE(SCRN,'(A)')' '

      IF(PARTCCF == 1)THEN
   		CCF = 1.0 + 2*FREE_LEN/DIAP_SET(ISET)*(1.257D0 + 0.4*EXP(-0.55D0*DIAP_SET(ISET)/FREE_LEN))
	  ELSE if(PARTCCF == 0)then
      	CCF = 1.0
   	  END IF

   END IF

   RADC = RADA*LAMBDA_SET(ISET)
   !
   !:::::::::::::::::::::::::::::
   !PARTICLE VOLUME, SURFACE AREA
   !:::::::::::::::::::::::::::::
	!VOLUME OF NON-SPHERICAL PARTICLE
	PVOL = FOURTHIRD*PIE*RADA**3*LAMBDA_SET(ISET)
   !
   !:::::::::::::::::::::::::::::
   !PARTICLE VOLUME, SURFACE AREA
   !:::::::::::::::::::::::::::::
	!VOLUME OF NON-SPHERICAL PARTICLE
	PVOL = FOURTHIRD*PIE*RADA**3*LAMBDA_SET(ISET)
	IF(LAMBDA_SET(ISET) < 1.0)THEN
      SHAPE(ISET) = 'OBLATE'
      RK1 = SQRT(1.0 - (RADC**2/RADA**2))
      RK2 = (1.0 - RK1**2)/RK1
      PASA = 2.0*PIE*RADA**2*(1.0 + RK2*ATANH(RK1))
   ELSE IF(LAMBDA_SET(ISET) == 1.0)THEN
      SHAPE(ISET) = 'SPHERE'
		!ACTUAL AREA OF NON-SPHERICAL PARTICLE
		PASA = 4.0D0*PIE*RADA**2
	ELSE IF(LAMBDA_SET(ISET) > 1.0)THEN
		SHAPE(ISET) = 'PROLATE'
		!ACTUAL AREA OF NON-SPHERICAL PARTICLE
		RK1 = SQRT(1.0 - (RADA**2/RADC**2))
		RK2 = RADC/(RADA*RK1)
		PASA = 2.0*PIE*RADA**2*(1.0 + RK2*ASIN(RK1))
	END IF

   !::::::::::::::::::::::::::::::::::::::
	!EQUIVALENT SPHERICAL DIAMETER (VOLUME)
   !::::::::::::::::::::::::::::::::::::::
   ESDV = (6.0D0*PVOL/PIE)**(ONETHIRD)
   !::::::::::::::::::::::::::::::::::::
 	!EQUIVALENT SPHERICAL DIAMETER (AREA)
	!::::::::::::::::::::::::::::::::::::
   ESDA = SQRT(PASA/PIE)
   !:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
	!SURFACE, PROJECTED AREAS AND SPHERICITY
   !surface of a sphere area having the same volume as the NON-SPHERICAL particle
 	!surface area of the volume equivalent sphere = SPHVOL
   !:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
	SPHVOL=PIE*ESDV**2
 	!PARTICLE SPHERICITY, PSN
   PSN = SPHVOL/PASA
   !+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 	!------------		SURFACE, PROJECTED AREAS AND SPHERICITY		-----------------
 	!
 	! surface of a sphere area having the same volume as the NON-SPHERICAL particle
 	! surface area of the volume equivalent sphere
 	! surface area of a sphere = 4*PIE*RADIUS**2  = PIE*DIAMETER**2
   SPHVOL=PIE*ESDV**2
 	!PARTICLE SPHERICITY
   PS_NORM(ISET)=SPHVOL/PASA

	!:::::::::::::
	!PARTICLE MASS
	!:::::::::::::
	MASS = DENP_SET(ISET)*PVOL
	!::::::::::::::::::::::::::::::
 	!MOMENT OF INERTIA OF SPHERIODS
	!::::::::::::::::::::::::::::::
	MOMX = (1 + LAMBDA_SET(ISET)**2)*RADA**2*MASS/5.0D0
    MOMY = MOMX
    MOMZ = 2.0D0*RADA**2*MASS/5.0D0

   !:::::::::::::::::::::::::::::::::::::::::::::::::
   !SAVE STATE VARIABLES TO BE USED DURINGN ITERATION
   !:::::::::::::::::::::::::::::::::::::::::::::::::
   PSTATE(01,ISET) = LAMBDA_SET(ISET)
	PSTATE(02,ISET) = RADA
	PSTATE(03,ISET) = ESDV
	PSTATE(04,ISET) = PST_SET(ISET)
	PSTATE(05,ISET) = MASS
	PSTATE(06,ISET) = DENP_SET(ISET)
	PSTATE(07,ISET) = PSN
	PSTATE(08,ISET) = CCF
   !
   RSTATE(07,ISET) = MOMX
	RSTATE(08,ISET) = MOMY
	RSTATE(09,ISET) = MOMZ
END DO

DO ISET = 1,NPSET
	DO IP = 1,NPART
      JPART = IP + (ISET - 1)*NPART
      PART(08,JPART) = PSTATE(03,ISET)
      PART(09,JPART) = PSTATE(02,ISET)
      PART(10,JPART) = PSTATE(05,ISET)
   END DO
END DO
!::::::::::::::::::::::::::::::::::::::
!INITIALISE THE SEED FOR RANDOM NUMBERS
!::::::::::::::::::::::::::::::::::::::
DO ISET = 1, NPSET
   NSEEDX0(ISET) = -(701*ISET)
   NSEEDY0(ISET) = -(702*ISET)
   NSEEDZ0(ISET) = -(703*ISET)

   NSEEDX1(ISET) = -550*ISET
   NSEEDY1(ISET) = -551*ISET
   NSEEDZ1(ISET) = -552*ISET

   NSEEDX2(ISET) = -(21*ISET)
   NSEEDY2(ISET) = -(22*ISET)
   NSEEDZ2(ISET) = -(23*ISET)

   NSEEDX3(ISET) = -(1110*ISET)
   NSEEDY3(ISET) = -(1111*ISET)
   NSEEDZ3(ISET) = -(1112*ISET)

   NSEEDX4(ISET) = -4*ISET
   NSEEDY4(ISET) = -5*ISET
   NSEEDZ4(ISET) = -6*ISET
END DO
!


!::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
!::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
!:::::::		END OF PARTICLE SIZING, DENSITY, STOKE NUMBER		::::::::::
!::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
!::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
!
!*********************
CALL PART_ALLOCATE(50)
!*********************
!INDICES OF DOMAIN WHERE SOLUTION IS OBTAINED
ISTR = 2
JSTR = 2
KSTR = 2
IEND = L
JEND = M
KEND = N
!
JK = JO(JSTR) + KO(KSTR)
IK = ISTR + KO(KSTR)
IJ = ISTR + JO(JSTR)
!

BWALL(2) = X(ISTR+JK)
BWALL(1) = X(IEND+JK)
BWALL(4) = Y(IK+JO(2))
BWALL(3) = Y(IK+JO(M))
BWALL(5) = Z(IJ+KO(N))
BWALL(6) = Z(IJ+KO(2))
!

XSEC(1) = ABS(BWALL(2) - BWALL(1))
XSEC(2) = ABS(BWALL(4) - BWALL(3))
XSEC(3) = ABS(BWALL(6) - BWALL(5))
!
!WRITE MESSAGE TO FILE: UNIT 200
!---------------------
CALL PART_MESSAGE(201)
!---------------------
!
!ZERO ALL STATISTICAL VARIABLES TO ZERO
CALL PART_STAT_ZERO
!
CROSS_N = 0
CROSS_S = 0
CROSS_E = 0
CROSS_W = 0
CROSS_R = 0
CROSS_L = 0
INDEX  = 0
INDEX_OUT = 0

IF(PART_INTERACT)THEN
	IF(.NOT. ALLOCATED(INDEX_COL_COUNT))ALLOCATE(INDEX_COL_COUNT(NPART*NPSET))
	INDEX_COL_COUNT = 1
	IF(.NOT. ALLOCATED(IPOPULATION))ALLOCATE(IPOPULATION(10))
	IPOPULATION = 0
   IF(.NOT. ALLOCATED(COLLISION_COUNT))ALLOCATE(COLLISION_COUNT(0:3))
   !COLLISION_COUNT COUNTS THE NUMBER OF TIMES BOUNC, COALE OR AGGLOM OCCURED
   COLLISION_COUNT = 0
   COLLISION_COUNT_TEMP = 0
   IF(.NOT. ALLOCATED(COLFILE))ALLOCATE(COLFILE(0:4))
   ! OPEN FILES FOR COLLISION
   !-----------------------
   CALL PART_OPENFILES(500)
   !-----------------------
END IF

! OPEN FILES FOR DEPOSITION AND FORCE ANALYSES
!-----------------------
CALL PART_OPENFILES(300)
!-----------------------
IF(LPTREAD)THEN
  	!READ RESTART FILE FOR PARTICLE
   CALL PART_RESTART
  	LPTREAD = .FALSE.
END IF
!
WRITE(SCRN,*)'LPT LEAVES PART_INPUT SUBROUTINE'

RETURN
END SUBROUTINE PART_INPUT
!
!:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
!:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
!:::::::::::::::::::		PART_STAT_ZERO		::::::::::::::::::::::::
!:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
!::	DESCRIPTION: SUBROUTINE TO ZERO PARTICLE STATISTICS PARAMETERS	::::
!::	CREATED: DR DERRICK O. NJOBUENWU, DATE: 26 MARCH 2013 12:02:23 GMT :
!::	CONTACT: IPSE, SPEME, UNIVERSITY OF LEEDS, LEEDS, LS2 9JT, UK	::::
!::	EMAIL:	 D.O.NJOBUENWU@LEEDS.AC.UK, DONADVISER@GMAIL.COM
!::	DATE MODIFIED:
!:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
!:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
!
SUBROUTINE PART_STAT_ZERO
!
USE  FDIM_MODULE
USE  FGRID_MODULE
USE  FVAR_MODULE
USE  FTURB_MODULE
USE  FTIME_MODULE
USE  FFILE_MODULE
USE  FLOGICAL_MODULE
USE  FCPUTIME_MODULE
USE  PART_NUM_MODULE
USE  PART_COUNT_MODULE
USE  PART_INITIAL_MODULE
USE  PART_LOGICAL_MODULE
USE  PART_STAT_MODULE
USE  PART_VECTOR_MODULE
USE  PART_TIME_MODULE
USE  PART_PROP_MODULE
USE  PART_EXTRA_MODULE
USE  PART_SGS_MODULE
USE  GEO_SIZE_MODULE
USE  FROTAT_MODULE
USE  PART_PWI_MODULE
USE  PART_PDF_MODULE
USE  PART_CONCEN_MODULE
USE  FUTILITY_MODULE
USE  PART_DEPOSIT_MODULE
USE  PART_FILENAME_MODULE
USE  PART_PSTATE_MODULE
USE  PART_FLAG_MODULE
!
IMPLICIT NONE
!
INTEGER	::	K,IJ
!
WRITE(SCRN,*)'LPT ENTRES PART_STAT_ZERO SUBROUTINE'
!
MOVIE_COUNT=0
MOVIE_START=0
PDFCOUNT=0.0
PARTICLESAMPLECOUNT=0
!
IF(PART_STATIST)THEN
   !PARTICLE VELOCITY MEAN AND RMS USING NSTEP
   PSTATCOUNT=0
   PSTAT=0.0
END IF
IF(FORCE_RATIO)THEN
   FORCEDT = 0
   FORCENORM = 0
END IF
IF(DEPOSITION)THEN
   DEPOSITNUM = 0
   DEPTIM = 0.0
   DEPOSIT_N = 0
   DEPOSIT_S = 0
   DEPACTIVE = 0

   KINT = (NP1 -2)/DSLAB
   IJ = 2 + JO(2)
   IF(.NOT.ALLOCATED (KSLAB))ALLOCATE (KSLAB(DSLAB+1))
   IF(.NOT.ALLOCATED (ZSLAB))ALLOCATE (ZSLAB(DSLAB+1))
   KSLAB(1) = KSTR
   ZSLAB(1) = Z(IJ+KO(KSLAB(1)))
   DO K = 2, DSLAB
      KSLAB(K) = KSLAB(K-1) + KINT
      ZSLAB(K) = Z(IJ+KO(KSLAB(K)))
   END DO
   KSLAB(DSLAB+1) = KEND
   ZSLAB(DSLAB+1) = Z(IJ+KO(KSLAB(DSLAB+1)))
   KK1 = INT(0.25*DSLAB)
   KK2 = NINT(0.75*DSLAB)
	CALL PART_MESSAGE(202)
END IF

WRITE(SCRN,*)'LPT LEAVES PART_STAT_ZERO SUBROUTINE'
RETURN
END SUBROUTINE PART_STAT_ZERO
